insert into Region(nombreRegion) values ('America del Sur')
insert into Region(nombreRegion) values ('America Central')
insert into Region(nombreRegion) values ('America del Norte')
insert into Pais(nombrePais,idRegion) values ('Peru',1)
insert into Pais(nombrePais,idRegion) values ('Chile',1)
insert into Pais(nombrePais,idRegion) values ('Colombia',1)
insert into Pais(nombrePais,idRegion) values ('Mexico',2)
insert into zona_horaria(nombreZonaHoraria) values ('UTC-5')
insert into zona_horaria(nombreZonaHoraria) values ('UTC-6')
insert into zona_horaria(nombreZonaHoraria) values ('UTC-7')
insert into ciudad(nombreCiudad,idPais,idZonaHoraria) values ('Lima',1,1)
insert into ciudad(nombreCiudad,idPais,idZonaHoraria) values ('Guadalajara',4,1)
insert into ciudad(nombreCiudad,idPais,idZonaHoraria) values ('Valparaiso',2,1)
insert into servidor(nombreServidor,idCiudad) values ('Server Chile Valparaiso',3)
insert into servidor(nombreServidor,idCiudad) values ('Server Mexico Guadalajara',2)
insert into servidor(nombreServidor,idCiudad) values ('Server Peru Lima',1)
insert into videojuego(nombreVideojuego,numcompetidores) values ('Dota 2',25)
insert into videojuego(nombreVideojuego,numcompetidores) values ('League of legends',25)